### ISSUE TITLE
Issues to Fix

### ISSUE THREAD

**Issue by otag30** [SchoolOfCode/final-project-the-fitness-programmers#17]
```[tasklist]
### Tasks
- [x] Home Screen (Dashboard doesnt scroll fully down)
- [x] Water intake Screen: Water target (Basic MVP) needs to be changed to fixed value (not drop down) to allow with Backend
- [ ] Water Intake: Daily Water Intake should accept negative values
- [ ] Workout screen: Duration  Input minutes should not accept negative values
- [ ] fix motivational responsiveness
- [x] align style for login/setup/setup-details pages: signup-details: change icons color to teal, chnage submit button text color from white to grey. In the sign-up page top text chnage the (,) to "and".
```

```[tasklist]
### Tasks
```
