### ISSUE TITLE
Create motivation quote

### ISSUE THREAD

**Issue by Isuu1** [SchoolOfCode/final-project-the-fitness-programmers#6]
```[tasklist]
### Tasks
- [x] Install React Hot Toast
- [x] Attach onlick to corresponding button in bottom navbar
- [x] Style Hot Toast
```
